import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def get_llm_score(text: str) -> float:
    """
    Ask Groq whether the text reads as human or AI-generated.
    Returns a float 0.0–1.0 where 1.0 = confident AI-generated.
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a JSON object with two fields:
- "score": a float between 0.0 and 1.0, where 0.0 means definitely human-written and 1.0 means definitely AI-generated
- "reasoning": one sentence explaining your assessment

Text to analyze:
\"\"\"{text}\"\"\"

Respond with only the JSON object, no other text."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    parsed = json.loads(raw)
    score = float(parsed["score"])

    # Clamp to 0.0–1.0 just in case
    return max(0.0, min(1.0, score))


# Test it directly when you run this file
if __name__ == "__main__":
    tests = [
        ("Clearly AI", "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications."),
        ("Clearly human", "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it and i was thirsty for like three hours after."),
    ]

    for label, text in tests:
        score = get_llm_score(text)
        print(f"{label}: {score:.2f}")