import os
import json
import math
import re
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def get_llm_score(text: str) -> float:
    """
    Ask Groq whether the text reads as human or AI-generated.
    Returns a float 0.0–1.0 where 1.0 = confident AI-generated.
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a JSON object with two fields:
- "score": a float between 0.0 and 1.0, where 0.0 means definitely human-written and 1.0 means definitely AI-generated
- "reasoning": one sentence explaining your assessment

Text to analyze:
\"\"\"{text}\"\"\"

Respond with only the JSON object, no other text."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    parsed = json.loads(raw)
    score = float(parsed["score"])
    return max(0.0, min(1.0, score))


def get_stylo_score(text: str) -> float:
    """
    Measures sentence length variance and punctuation density.
    Returns a float 0.0–1.0 where 1.0 = structurally AI-like (uniform).
    """
    sentences = re.split(r'[.!?]+', text.strip())
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5  # Not enough text to score reliably

    # Sentence length variance (low variance = AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Normalize: std_dev of 0 = AI-like (1.0), std_dev of 10+ = human-like (0.0)
    variance_score = max(0.0, 1.0 - (std_dev / 10.0))

    # Punctuation density (low density = AI-like)
    expressive_punct = len(re.findall(r'[,\-—…!?]', text))
    density = expressive_punct / len(sentences)
    # Normalize: density of 0 = AI-like (1.0), density of 5+ = human-like (0.0)
    punct_score = max(0.0, 1.0 - (density / 5.0))

    return (variance_score + punct_score) / 2.0


def combine_scores(llm_score: float, stylo_score: float) -> float:
    """70% LLM, 30% stylometric."""
    return round((0.70 * llm_score) + (0.30 * stylo_score), 4)


def get_label(confidence: float) -> str:
    if confidence > 0.75:
        return "Attribution unclear — Our automated analysis found patterns consistent with AI-generated text. This is a signal, not a certainty. Use the appeal button below to contest this."
    elif confidence >= 0.45:
        return "Attribution uncertain — Our analysis could not determine whether this was written by a person or generated by AI. We've flagged this so you have the context, not to make a judgment."
    else:
        return "Appears human-written — Our analysis found no strong indicators of AI generation. This reflects our best assessment, not a guarantee."


def get_attribution(confidence: float) -> str:
    if confidence > 0.75:
        return "likely_ai"
    elif confidence >= 0.45:
        return "uncertain"
    else:
        return "likely_human"